arrikto/oidc-authservice

- go.mod
- go.sum
Go modules automatically pick v1.0.0 of the yosssi/boltstore library, which doesn't contain quite a few commits.
This PR updates the library version to the latest commit in master.
Maybe a fix for: https://github.com/arrikto/oidc-authservice/issues/2
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>
> deps: update boltstore library

- LICENSE
- README.md
- e2e/e2e_test.go
- handlers.go
- main.go
- state.go
- state_test.go
- util.go
This PR:
* Adds the MIT LICENSE file, same as the ajmyyra/ambassador-auth-oidc project
* Amends the MIT LICENSE file to include copyright to ajmyyra/ambassador-auth-oidc
* Adds license headers to all go source files.
* Fixes project name in README.
/assign @vkoukis 
/assign @iliastsi 
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>
> add LICENSE and copyright notices

- README.md
- handlers.go
- main.go
- util.go
Without this patch, when connecting to a self-hosted Dex instance that
is providing a self-signed certificate, the auth service fails to start
with the error message:
```
OIDC provider setup failed, retrying in 10 seconds: Get https://example-dex:32000/.well-known/openid-configuration: x509: certificate signed by unknown authority
```
This change adds a CA_BUNDLE environment variable which allows the user
to specify a CA bundle that can validate the OIDC server's certificate,
which will enable the auth service to start and to securely reach the
OIDC provider to authenticate a user.
Fixes https://github.com/arrikto/oidc-authservice/issues/9
> Add CA_BUNDLE to auth service server

- Makefile
- README.md
- e2e/e2e_test.go
- errors.go
- go.mod
- go.sum
- oidc.go
- oidc_test.go
- revoke.go
- server.go
The `UserInfo` function of the `go-oidc` library doesn't expose details
about the HTTP response from the OIDC Provider, if the request fails.
This makes it impossible to detect if the returned code is `401`, in
which case the user's session at the AuthService should be revoked.
Initially, we were revoking the session on any error, but this caused
undesired revocations because of errors we hadn't thought of (context
cancellation).
Reimplement the call to UserInfo and expose HTTP response details to the
caller, so they can make a sensible decision.
Related: https://github.com/coreos/go-oidc/issues/248
> oidc: Reimplement userinfo for fine-grained error handling

- authenticator_session.go
- authorizer_groups.go
- e2e/e2e_test.go
- e2e/manifests/authservice/base/kustomization.yaml
- e2e/manifests/authservice/base/params.env
- e2e/manifests/authservice/base/params.yaml
- main.go
- server.go
- session.go
- util.go
This PR contains a bugfix, where we didn't pass the oauth2config all the way to the session-authenticator.
In addition, it improves the UX when the user is not authorized.
When the user is using a browser and is not authorized, they will simply get a 403 page with a message explaining they can't access the upstream. However, there is no way to continue from there (e.g., logout), which makes for a bad UX.
Remedy this by:
- Revoking the user's session if they are unauthorized.
- Returning a message with a link to continue to login.
The branch `feature-plumb-oauth-config-v1` includes an extra commit for an additional check (don't create session if user is not authorized), however, I propose we don't do that.
As for how to test this PR, here is how I tested manually:
- To test the bugfix:
1. …
> minor bugfix + improve authorization ux

- Dockerfile
There are known security vulnerabilities in earlier versions of Go.
Also upgrade the base image to Alpine 3.12 and use that as a base to
build the code too (no need in pulling a larger Debian image for the
build, it doesn't buy us anything).
cc @asetty
> Dockerfile: Upgrade to go1.15.3 and alpine3.12

- README.md
- authenticator_idtoken.go
- main.go
- settings.go
The id token authenticator verifies the token in the header.
The header name of id token is specified by the `ID_TOKEN_HEADER`
config. The authenticator retrieves the USERID_CLAIM after the
verification. If there is no id token header, the verification failes
or the USERID_CLAIM does not exist, the request is passed to the
next authenticator.
> feature: add an id token authenticator

- state.go
PR #51 introduce the oidc_state_csrf cookie for protecting against CSRF
attacks in the OIDC flow. However, the cookie's path is not set, meaning
that the browser will only send it for the path where it was set. Thus,
login cannot be completed successfully. This commit sets the cookie's
path to `/`, same as the session cookie.
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>
**Requirements:**
- Make sure your PR conforms to our [contribution guidelines](../CONTRIBUTING.md)
> oidc: Set Path for csrf cookie

- server.go
- state.go
- util_test.go
When `AFTER_LOGIN_URL` is set, after the user is authenticated
`authservice` will redirect the user to the predefined url
defined by `AFTER_LOGIN_URL` and the original path is lost.
With this commit we introduce a new query parameter `next` that
is added when redirecting to `AFTER_LOGIN_URL` that has the
value of the original url that the user first visited.
Also we extended the stored state database to include the
original query parameters. Many applications keep their
internal state in query parameters and it's important
to preserve these values during redirection.
Signed-off-by: Ioannis Bouloumpasis <buluba@arrikto.com>
Closes: #66
> server: Propagate the original URL

- e2e/e2e_test.go
- hack/binary_deps.py
**Which issue is resolved by this Pull Request:**
None
**Description of your changes:**
The GitHub Workflows for the repository are currently failing.
Here's the current situation:
1. Kernel versions after 5.12.2 made sysctl variable `nf_conntrack_max` read-only for non-init net namespaces (https://github.com/torvalds/linux/commit/2671fa4dc0109d3fb581bc3078fdf17b5d9080f6). This change was backported to earlier kernel versions as well.
2. K3s minor versions before {1.18.19, 1.19.11, 1.20.7, 1.21.1} by default insist on setting this variable and break otherwise.
3. On their 2021/07/26 update, GH Actions bumped the kernel version of the GH-hosted runners to `5.4.0-1055-azure`. This kernel upgrade broke our GH Workflow because it included change (1).
In order to fix this, we must use a K3s …
> e2e: Upgrade K3d and K3s versions, fix CI breakage

- revoke.go
**Description:**
We have integrated PingID with Kubeflow, using AuthService and the OIDC 
protocol. During the logout, the revocation of the ``refresh`` and ``access`` 
tokens fails. This is because the current implementation of the 
`oidc-authservice` does not follow the ``RFC7009`` specification.
In this PR we implement the RFC7009 specification which states
the following:
> Implementations MUST support the revocation of refresh tokens 
> and SHOULD support the revocation of access tokens...
Token Revocation: (https://datatracker.ietf.org/doc/html/rfc7009#section-2)
The current ``oidc-authservice`` implementation does **not** tolerate 
any error during the revocation of both the ``refresh`` and the ``access`` 
tokens. To implement the aforementioned specification we modify the …
> oidc: enable the revocation of the refresh and access tokens (PingID)

- authenticator_idtoken.go
- authenticator_session.go
- server.go
- session.go
- util.go
- web_server.go
Improve log messages so that they provide a more accurate/clear picture
of the execution/authentication state:
* Include the `context` string in log entries to show the name of the
software module generating each message. Possible contexts currently:
- `server`
- `web server`
- `session authenticator`
- `idtoken authenticator`
- `kubernetes authenticator`
* Add Authenticator Start messages
* Add Authenticator Success message
* Add messages wherever missing in the authentication process
Refs arrikto/dev#1711
Signed-off-by: Phoevos Kalemkeris <phoevos@arrikto.com>
> logs: improve log messages

- README.md
- authenticator_idtoken.go
- authenticator_kubernetes.go
- authenticator_session.go
- main.go
- server.go
- session.go
- settings.go
- util.go
Add header to inform upstream app (i.e. Rok, KFP) about the authn method
used. More specifically, on successful authentication, an 'Auth-Method'
header is added to the request, with its value depending on the
authenticator that completed the authentication process and the method
used:
* `authenticator_session`:
On authn success, sets `Auth-Method` header to:
- `header` if a session ID token was used
- `cookie` if a session cookie was used
* `authenticator_idtoken`:
On authn success, sets `Auth-Method` header to `header`
* `authenticator_kubernetes`:
On authn success, sets `Auth-Method` header to `header`
Refs arrikto/dev#965
Signed-off-by: Phoevos Kalemkeris <phoevos@arrikto.com>
> authenticators: Add Auth-Method header

- oidc.go
- oidc_test.go
Some external Identity Providers deviate from the standard OpenID spec (https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims). One particular divergence from the spec is that their `/userinfo` endpoint responds with a `string` value for the EmailVerified field. The spec specifies that this field should accept `bool` values. We want to extend AuthService to cover this as well.
This is the case for Identity Providers such as:
* Apple: https://developer.apple.com/forums/thread/121411 
* PayPal: https://community.auth0.com/t/userinfo-email-verified-field-string-boolean-or-both/27553
* AWS Cognito: https://forums.aws.amazon.com/thread.jspa?threadID=324806
For these Identity Providers, AuthService fails with:
```
level=error msg="Not able to fetch userinfo: oidc: failed to …
```
> oidc: handle email_verified for bool and string values

- README.md
- authenticator_kubernetes.go
- go.mod
- go.sum
- main.go
- server.go
- settings.go
- util.go
Introduce a caching mechanism for AuthService. When enabled,
AuthService will store freshly authenticated **Bearer Token** in its 
cache for a configurable amount of time. Contrary to the existing
implementation when a client makes a request with a bearer token
in its Authorization header, then **AuthService will examine if this
bearer token is cached**:
* If it is, then AuthService will retrieve the
corresponding cached **User Info** and will skip the authenticators.
In this case we consider that the client was successfully authenticated.
* Otherwise, if the bearer token does not exist in the cache, then 
AuthService will try the available authenticators one-by-one until one
of them successfully authenticates the client. Then AuthService will
retrieve the corresponding **User Info** and …
> Add caching mechanism in AuthService

- README.md
- authenticator_jwt.go
- authenticator_jwt_test.go
- errors.go
- main.go
- server.go
- settings.go
- util.go
In this PR, we introduce:
1. a new JWT access token authenticator. 
2. a disable functionality for specific authenticators
We utilize the `go-oidc` implementation of the ID Token verifier (which we already use for the ID Token authenticator). Additionaly, we perform some local checks to validate whether or not the received request was intended to be validated by the JWT authenticator. If the request was indeed destined for this authenticator then AuthService checks none of the rest of the available authenticators.
The idea is to perform **locally the necessary validation** for the received access tokens based on the signatures of the JWT access tokens.
Our implementation should meet the following **requirements**:
Once AuthService receives a JWT access token it has to . Our new …
> Introduce JWT access token authenticator and disable-authenticator functionality

- main.go
- server.go
After embracing the AuthService Caching Mechanism effort (https://github.com/arrikto/oidc-authservice/pull/87), we suggest reordering the authentication methods that AuthService is using. The only authentication method that benefits from the caching mechanism is the `authenticator_kubernetes.go`. This means that the authentication of a Kubernetes-provided token will have to wait until AuthService tries-and-fails for both the Session authentication method and the ID Token authentication method. Since the caching mechanism can really reduce the authentication overhead and boost the performance, it would make sense for AuthService to try out the Kubernetes authentication method first.
**Description of your changes:**
The current order of the authentication methods that AuthService is …
> Reorder the authentication methods

- README.md
- authenticator_opaque.go
- authenticator_opaque_test.go
- go.mod
- go.sum
- main.go
- oidc.go
- server.go
- settings.go
We should extend AuthService to support the authentication of opaque access tokens. This method is also known as **remote access token validation method**. 
The overall idea is:
1. **AuthService** receives a request with an opaque access token in the Authorization header of the request.
2. **AuthService** retrieves the opaque access token from the header of the incoming request.
3. **AuthService** makes a GET request to the `/userinfo` endpoint of the integrated external Identity Provider with this opaque token in the Authorization header of the outcoming request.
4. If the token is valid and has not expired, then the **Identity Provider** should respond with a list of claims for this user. For example:
```
{
"family_name" : "Markou",
"nickname" : "zep",
"preferred_username" : …
```
> Opaque Access Token Authentication Method

- Dockerfile
Upgrade the base image to `alpine:3.16` to eliminate the following critical CVEs:
* CVE-2022-2068
* CVE-2022-37434
> Upgrade base image to eliminate CVEs

- README.md
- authorizer_external.go
- authorizer_external_test.go
- go.mod
- go.sum
- main.go
- server.go
- settings.go
Introduce a new authorizer that relies on an external service to authorize the requests.
Authservice will send a POST request to the external authorizer with body in the following format:
{
"timestamp": "timestamp of the request",
"user": {
"name": "username",
"id": "user id",
"groups": ["a list of groups"],
"extra": {// object with extra info},
"claims": {// object with the JWT claims, if JWT was used}
},
"request": {
"host": "the request host",
"method": "the request HTTP method",
"path": "the request patch",
"port": "the request port"
}
}
The external service should respond with code [200, 300) if the request is authorized or 401|403 not.
The external authorizer is enabled by setting the 'EXTERNAL_AUTH_URL' to the target authorization service (e.g. …
> authorizers: Add new external authorizer

- authorizer_external.go
- authorizer_external_test.go
Fix a bug that triggered panic when a request's HOST header did not have the port number.
Signed-off-by: Ioannis Bouloumpasis <buluba@arrikto.com>
> external-authorizer: Fix when request HOST doesn't have port

- README.md
- authenticators/idtoken.go
- authenticators/jwt.go
- authenticators/opaque.go
- authenticators/session.go
- authorizer_external.go
- common/settings.go
- common/util.go
- main.go
- oidc/oidc.go
- oidc/revoke.go
- server.go
- sessions/redis.go
- sessions/session.go
- web_server.go
During live debug sessions we realized that the AuthService logs are way too verbose and thus not helpful for debugging. Since all requests are passed through AuthService for authentication we have a chunk of logs for every one of the requests, even for requests to whitelisted URLs.
As you can see in the repo there is an upstream PR which dates back to 2019 (https://github.com/arrikto/oidc-authservice/pull/3). This PR introduces a new `LOG_LEVEL` envvar that expects one of the following values:
* `warn`
* `info`
* `debug`
The functionality that the contributor has added seems to be in the right direction. But a lot has changed since they submitted this PR. So we had better start fresh and lay out a plan that complies with the latest `oidc-authservice`.
We need to **re-categorize** our log …
> Set log level from a new `LOG_LEVEL` env var.

- authenticators/opaque.go
- authenticators/session.go
- oidc/oidc.go
- oidc/oidc_test.go
- server.go
- sessions/session.go
This PR introduces the following changes:
* Update access and refresh tokens in session if the ones stored in db have expired and been refreshed.
* Trigger the session update regardless of strict validation mode to ensure token validity.
The above will eliminate unnecessary requests to the OIDC provider.
Signed-off-by: Athina Plaskasoviti <athinapl@arrikto.com>
> Update access and refresh tokens in session
